config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :articles
	root "pages#home"
	resources :users
	get "login", to: "sessions#new"
	post "login", to: "sessions#create"
	delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: { minimum: 2, maximum: 50 }
	validates :description, presence: true, length: { minimum: 4, maximum: 200 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :articles
	validates :username, presence: true,
		uniqueness: { case_sensitive: false },
		length: {minimum: 3,maximum: 20 }
	VALID_EMAIL = /\A[\w.+-]+@\w+\.\w+\z/
		validates :email, presence: true,
		uniqueness: { case_sensitive: false },
		length: { maximum: 150 },
		format: { with: VALID_EMAIL }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user , :logged_in

	def current_user
		@cur_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in
		is_logged = !!User.find(session[:user_id]) if session[:user_id];
		return !!is_logged
	end

	def is_logged
		if !logged_in
			flash[:alert] = "Hey there You need to login first"
			redirect_to login_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :fetch_article, only: [:show, :edit, :update, :destroy]
	before_action :is_logged, only: [:update, :edit, :destroy]
	before_action :user_privilezed, only: [:update, :edit, :destroy]
	def show
	end

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(filter_param)
		@article.user = current_user
		if @article.save
			flash[:notice] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render "new"
		end
	end

	def update
		if @article.update(filter_param)
			flash[:notice] = "Article was updated successfully"
			redirect_to article_path(@article)
		else
			render "edit"
		end
	end

	def edit
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	private

	def fetch_article
		@article = Article.find(params[:id])
	end

	def filter_param
		return params.require(:article).permit(:title, :description)
	end

	def user_privilezed
		if @article.user != User.find(session[:user_id])
			flash[:alert] = "You don't have the authorities to access the page"
			redirect_to @article
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to user_path(current_user) if logged_in
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController   #for verifying and serving the loggedin page to user
	def new						       
		@session = User.new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			redirect_to user
		else
			flash.now[:alert] = "You entered wrong details"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have been logged out of the window"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController    
	def new
		@user=User.new
	end

	def show					#to display the logged in user page
		@user=User.find(params[:id])
	end

	def create					#for signup
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "You have successfully loggedin"
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/views/articles/_all_articles.html.erb
<h1 class="text-center">Articles Listing </h1>  
<% @articles.each do |article| %>
	<div class="card_size">
		<div class="card">
			<div class="card-header">By-
				<%= article.user.username %>
			</div>
			<div class="card-body">
				<h5 class="card-title"><%= article.title %></h5>
				<p class="card-text"><%= truncate(article.description, length: 60) %></p>
				<%= link_to 'Show', article_path(article), class: "btn btn-success" %>
				<% if logged_in && article.user == current_user %>
					<%= link_to 'Edit', edit_article_path(article), class: "btn btn-secondary ml-1" %>
					<%= link_to 'Delete', article_path(article), method: :delete, class: "btn btn-danger ml-1" %>
				<% end %>
			</div>
		</div>
	</div>
<% end %>
<p class="mt-5"><%= link_to 'Create new Article', new_article_path, class: "btn btn-success" %></p>

app/views/articles/_form_create_edit.html.erb
<% if @article.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<h4 class="alert-heading">It seems you did a mistake!!</h4>
		<ul>
			<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_with(model: @article, local: true) do |form| %>
	<div class="form-group col-sm-10">
		<%= form.label :title %><br>
		<%= form.text_field :title, class: "form-control"%>
	</div>

	<div class="form-group col-sm-10">
		<%= form.label :description, 'Article Description' %><br>
		<%= form.text_field :description, class: "form-control" %>
	</div>

	<p>
		<%= form.submit class: "btn btn-primary ml-3"%>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit Article</h1>
<%= render "form_create_edit" %>

app/views/articles/index.html.erb
<%= render "all_articles" %>

app/views/articles/new.html.erb
<h1 class="text-center">Create New Article</h1>
<%= render "form_create_edit" %>

app/views/articles/show.html.erb
<% flash.each do |f| %>
	<div class="alert alert-success" role="alert">
  	<%= f %>
	</div>
<% end %>
<h1 class="text-center"> Article Details </h1>
<div class="jumbotron">
	<h1 class="display-4"><%= @article.title %></h1>
	<p class="lead"><%= @article.description %></p>
	<hr class="my-4">
	<p>By- <%= @article.user.username %></p>
	<% if logged_in && @article.user == current_user%>
		<p class="lead">
		<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-secondary btn-lg" %>
		<%= link_to 'Delete', article_path(@article), method: :delete, class: "btn btn-secondary btn-lg" %>
		</p>
	<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Blogging App', root_path, class: "navbar-brand ml-3" %>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
																																			aria-controls="navbarSupportedContent" aria-expanded="false"
																																			aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" 
																																											 aria-haspopup="true" aria-expanded="false">
					More
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<%= link_to 'All Articles', articles_path,  class: "dropdown-item" %>
					<%= link_to 'Create Articles', new_article_path, class: "dropdown-item" %>
				</div>
			</li>
			<% if logged_in  %>
				<li class="nav-item">
					<%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
				</li>
				<li class="nav-item">
					<%= link_to  current_user.username, user_path(current_user), class: "nav-link" %>
				</li>
			<% else %>
				<li class="nav-item">
					<%= link_to 'SignUp', new_user_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to 'Login', login_path, class: "nav-link" %>
				</li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BloggingApp</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<%= render "/layouts/navbar" %>
		<%= yield %>
	</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1 class="display-4">Bloggin App</h1>
	<p class="lead">Here you can view articles all over the world and be a part of the community</p>
	<hr class="my-4">
	<p>Lets SignIn and get started!!</p>
	<p class="lead">
		<%= link_to 'SignIn', "/users/new", class: "btn btn-primary btn-lg" %>
	</p>
</div>

app/views/users/_form_create_edit.html.erb
<% if @user.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<h4 class="alert-heading">It seems you did a mistake!!</h4>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_with(model: @user, local: true) do |form| %>
	<div class="form-group col-sm-10">
		<%= form.label :username %><br>
		<%= form.text_field :username, class: "form-control"%>
	</div>

	<div class="form-group col-sm-10">
		<%= form.label :email, 'Enter Email' %><br>
		<%= form.email_field :email, class: "form-control" %>
	</div>

	<div class="form-group col-sm-10">
		<%= form.label :password, 'Enter password' %><br>
		<%= form.password_field :password, class: "form-control" %>
	</div>
	<p>
		<%= form.submit class: "btn btn-primary ml-3"%>
	</p>
<% end %>

app/views/users/new.html.erb
<h1 class="text-center">SignUp</h1>
<%= render "form_create_edit" %>

app/views/users/show.html.erb
<% if logged_in && @user.id == current_user.id %>
	<h1 class = "text-center mt-5 text-success">Welcome: <%= @user.username %></h1>
	<% @articles = @user.articles %>
	<%= render "articles/all_articles" %>
<% else %>
	<div class="alert alert-warning" role="alert">
  	Sorry this Id does not belong to you!!
	</div>
<% end %>